POST http://localhost:3001/api/notes/
Content-Type: application/json
{
    "content":"Hola que tal",
    "important":true
}
###
DELETE http://localhost:3001/api/notes/5
###
GET http://localhost:3001/api/notes/4


