POST http://localhost:3000/api/notes/
Content-Type: application/json

{
    "content":"Hola que tal, soy la nota 2",
    "important":true
}

###
PUT http://localhost:3000/api/notes/638cbf458011322dda733d14
Content-Type: application/json

{
    "content":"Hola que tal, soy la nota 1",
    "important":false
}

###

DELETE http://localhost:3000/api/notes/638cd39a5a31af494dd17c31

###
GET http://localhost:3000/api/notes/


